pipeline {
    agent any

    // Use Maven installed in Jenkins Global Tool Configuration
    tools {
        maven 'Mvn'  // Must match the name in Jenkins Global Tool Config
    }

environment {
    EC2_USER = 'ubuntu'
    EC2_HOST = '3.123.45.67'          // <-- Replace with your EC2 public IP
    EC2_KEY = '/var/jenkins_home/.ssh/April-lab.pem'
    APP_NAME = 'simple-java-maven-app'
    REMOTE_DIR = '/home/ec2-user/deploy'
}

    stages {

        stage('Checkout SCM') {
            steps {
                git url: 'https://github.com/RitikAg2710/simple-java-maven-app', branch: 'master'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Deploy to EC2') {
            steps {
                echo "Deploying $APP_NAME to EC2..."
                sh """
                    ssh -o StrictHostKeyChecking=no -i $EC2_KEY $EC2_USER@$EC2_HOST 'mkdir -p $REMOTE_DIR'
                    scp -o StrictHostKeyChecking=no -i $EC2_KEY target/*.jar $EC2_USER@$EC2_HOST:$REMOTE_DIR/
                """
            }
        }
    }

    post {
        success {
            echo "✅ Deployment Successful!"
        }
        failure {
            echo "❌ Deployment Failed!"
        }
    }
}
